<a href="https://colab.research.google.com/github/jaythorat/Age-Gussing-Game/blob/main/Movie_recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd

In [26]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [27]:
movies.merge(credits,on="title").shape

(4809, 23)

In [28]:
credits.shape

(4803, 4)

In [29]:
movies.shape

(4803, 20)

In [30]:
movies = movies.merge(credits,on="title")

In [31]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [37]:
# genres,id,keywords,title,overview,cast,crew
movies = movies.drop(['budget','homepage','original_language','original_title','popularity',"production_companies","production_countries","release_date","revenue","runtime","spoken_languages",'status',"tagline","vote_average","vote_count","id"],axis=1)

In [42]:
movies.head(0)

Empty DataFrame
Columns: [genres, keywords, overview, title, movie_id, cast, crew]
Index: []

In [46]:
movies.dropna(inplace=True)

In [54]:
# movies.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Length: 4806, dtype: bool

In [56]:
movies["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [58]:
import ast

def convert(obj):
  l = []
  for i in ast.literal_eval(obj):
    l.append(i["name"])
  return l

In [65]:
# movies['genres']=movies['genres'].apply(convert)

ValueError: ignored

In [66]:
movies['keywords'] =  movies['keywords'].apply(convert)

In [67]:
movies

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,El Mariachi,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,Newlyweds,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered",231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,[],[],When ambitious New York attorney Sam is sent t...,Shanghai Calling,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,My Date with Drew,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [69]:
def convert3(obj):
  l = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter != 3:
      l.append(i["name"])
    else:
      break
  return l

In [71]:
movies["cast"]= movies["cast"].apply(convert3)

In [72]:
movies

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,206647,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,El Mariachi,9367,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,Newlyweds,72766,"[Edward Burns, Kerry Bishé, Marsha Dietlein, C...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered",231617,"[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,[],[],When ambitious New York attorney Sam is sent t...,Shanghai Calling,126186,"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,My Date with Drew,25975,"[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [73]:
def fetch_director(obj):
  l = []
  for i in ast.literal_eval(obj):
    if i['job'] == "Director":
      l.append(i["name"])
      break
  return l

In [75]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [78]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [81]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "")for i in x])

In [82]:
movies

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,206647,"[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,49026,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,49529,"[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[El, Mariachi, just, wants, to, play, his, gui...",El Mariachi,9367,"[CarlosGallardo, JaimedeHoyos, PeterMarquardt,...",[RobertRodriguez]
4805,"[Comedy, Romance]",[],"[A, newlywed, couple's, honeymoon, is, upended...",Newlyweds,72766,"[EdwardBurns, KerryBishé, MarshaDietlein, Cait...",[EdwardBurns]
4806,"[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[""Signed,, Sealed,, Delivered"", introduces, a,...","Signed, Sealed, Delivered",231617,"[EricMabius, KristinBooth, CrystalLowe, GeoffG...",[ScottSmith]
4807,[],[],"[When, ambitious, New, York, attorney, Sam, is...",Shanghai Calling,126186,"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...",[DanielHsia]
4808,[Documentary],"[obsession, camcorder, crush, dreamgirl]","[Ever, since, the, second, grade, when, he, fi...",My Date with Drew,25975,"[DrewBarrymore, BrianHerzlinger, CoreyFeldman,...",[BrianHerzlinger]

In [83]:
movies["tags"] = movies["overview"] + movies["genres"]+ movies["cast"]+ movies["crew"]

In [85]:
movies["tags"][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'StephenLang',
 'MichelleRodriguez',
 'GiovanniRibisi',
 'JoelDavidMoore',
 'CCHPounder',
 'WesStudi',
 'LazAlonso',
 'DileepRao',
 'MattGerald',
 'SeanAnthonyMoran',
 'JasonWhyte',
 'ScottLawrence',
 'KellyKilgour',
 'JamesPatrickPitt',
 'SeanPatrickMurphy',
 'PeterDillon',
 'KevinDorman',
 'KelsonHenderson',
 'DavidVanHorn',
 'JacobTomuri',
 'MichaelBlain-Rozgay',
 'JonCurry',
 'LukeHawker',
 'WoodySchultz',
 'PeterMensah',
 'SoniaYee',
 'JahnelCurfman',
 'IlramChoi',
 'KylaWarren',
 'LisaRoumain',
 'DebraWilson',
 'ChrisMala',
 'TaylorKibby',
 'JodieLandau',
 'JulieLamm',
 'CullenB.Madden',
 'JosephBradyMadden',
 'FrankieTorres',
 'AustinWilson',
 'SaraWilson',
 'TamicaWashington-Miller',
 'LucyBriant',
 'NathanMeister',
 'GerryBlair',
 'MatthewChamberlain',
 'PaulYates',
 'WrayWilson',
 'JamesGaylyn',
 'MelvinLenoClarkIII',
 'CarvonFutrell',
 'BrandonJelkes',
 'MicahMoch',
 'HanniyahMuhammad',
 'ChristopherNolen',
 'ChristaOliver',
 'AprilMarieThomas',
 'BravitaA.Threatt',
 'ColinBleasdale',
 'MikeBodnar',
 'MattClayton',
 'NicoleDionne',
 'JamieHarrison',
 'AllanHenry',
 'AnthonyIngruber',
 'AshleyJeffery',
 'DeanKnowsley',
 'JosephMika-Hunt',
 'TerryNotary',
 'KaiPantano',
 'LoganPithyou',
 'StuartPollock',
 'Raja',
 'GarethRuck',
 'RhianSheehan',
 'T.J.Storm',
 'JodieTaylor',
 'AliciaVela-Bailey',
 'RichardWhiteside',
 'NikieZambo',
 'JuleneRenee',
 'JamesCameron']

In [95]:
new_df = movies[["movie_id","title","tags"]]

In [96]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x) )

<ipython-input-96-20f359eb4260>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x) )

In [99]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

<ipython-input-99-8b60b591a07f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [100]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [118]:
pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.8/dist-packages (3.7)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk) (2022.6.2)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk) (7.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk) (4.64.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk) (1.2.0)

In [103]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words="english")

In [111]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [113]:
vectors.shape()

TypeError: ignored

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1950s',
 '1960s',
 '1970s',
 '19th',
 '20',
 '200',
 '20th',
 '24',
 '25',
 '30',
 '40',
 '50',
 '60',
 '60s',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'aaronyoo',
 'aasifmandvi',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abrahambenrubi',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'account',
 'accused',
 'ace',
 'achieve',
 'act',
 'action',
 'actions',
 'activities',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adambrody',
 'adamgodley',
 'adamgoldberg',
 'adamlefevre',
 'adams',
 'adamsandler',
 'adamscott',
 'adamshankman',
 'adaptation',
 'addict',
 'addiction',
 'adewaleakinnuoye',
 'adopted',
 'adopts',
 'adrianmartinez',
 'adrianscarborough',
 'adrienbrody',
 'adult',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'aftermath',
 'agbaje',
 'age',
 'aged',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'ailing',
 'air',
 'airport',
 'ajaynaidu',
 'aka',
 'al',
 'alanalda',
 'alanarkin',
 'alancumming',
 'alanrickman',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrooks',
 'albertfinney',
 'alcoholic',
 'alecbaldwin',
 'alecguinness',
 'alessandronivola',
 'alex',
 'alexandersiddig',
 'alexanderskarsgård',
 'alexapenavega',
 'alexborstein',
 'alexisbledel',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'aliashawkat',
 'alice',
 'alicebraga',
 'alicedrummond',
 'aliciasilverstone',
 'aliciawitt',
 'alien',
 'aliens',
 'alike',
 'alilarter',
 'alisonlohman',
 'alisonpill',
 'alive',
 'allancorduner',
 'allen',
 'allencovert',
 'alleong',
 'alliance',
 'allied',
 'allies',
 'allisonjanney',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alunarmstrong',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amazing',
 'amberheard',
 'ambervalletta',
 'ambition',
 'ambitious',
 'america',
 'americaferrera',
 'american',
 'americans',
 'amid',
 'amidst',
 'amp',
 'amy',
 'amyadams',
 'amypoehler',
 'amyryan',
 'amysedaris',
 'amysmart',
 'anagasteyer',
 'analyst',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andreamartin',
 'andrebraugher',
 'andrew',
 'andrewdaly',
 'andrewstanton',
 'andy',
 'andydick',
 'andygarcía',
 'andyrichter',
 'andysamberg',
 'andyserkis',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angelo',
 'angry',
 'angusmacinnes',
 'animal',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annafaris',
 'annakendrick',
 'annalevine',
 'annapaquin',
 'annasophiarobb',
 'anndowd',
 'anne',
 'annebancroft',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annemoss',
 'annettebening',
 'annie',
 'annikapergament',
 'annual',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonylapaglia',
 'anthonymackie',
 'anti',
 'antics',
 'antonicorone',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartment',
 'apes',
 'apocalypse',
 'apocalyptic',
 'appear',
 'appears',
 'apple',
 'apprentice',
 'approaches',
 'april',
 'architect',
 'arcy',
 'area',
 'arielwinter',
 'arigraynor',
 'arise',
 'armed',
 'arminmueller',
 'arms',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'art',
 'arthur',
 'arthurj',
 'arthurtovey',
 'artist',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'aside',
 'ask',
 'asked',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'astronaut',
 'astronauts',
 'asylum',
 'atoessandoh',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audition',
 'august',
 'aunjanueellis',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'avaacres',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'azizansari',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bail',
 'bailey',
 'bailing',
 'baker',
 'balance',
 'ball',
 'ballet',
 'band',
 'banished',
 'bank',
 'banker',
 'baptiste',
 'bar',
 'barbarahershey',
 'barbrastreisand',
 'barely',
 'bargained',
 'barney',
 'barry',
 'barrylevinson',
 'barrypepper',
 'barryshabakahenley',
 'bars',
 'base',
 'baseball',
 'based',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'bay',
 'bdwong',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beaubridges',
 'beautiful',
 'beauty',
 'beccasweitzer',
 'bed',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'beloved',
 'ben',
 'benaffleck',
 'benchaplin',
 'benedictcumberbatch',
 'benedictwong',
 'benfoster',
 'bengazzara',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstiller',
 'bent',
 'benwhishaw',
 'berlin',
 'bernardhill',
 'bernardlee',
 'berniemac',
 'best',
 'bet',
 'beth',
 'bethgrant',
 'betrayal',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'beverlyd',
 'big',
 'bigger',
 'biggest',
 'biker',
 'billcamp',
 'billcobbs',
 'billduke',
 'billhader',
 'billionaire',
 'billmoseley',
 'billmurray',
 'billnighy',
 'billnunn',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyburke',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'billydeewilliams',
 'billyslaughter',
 'billywest',
 'billyzane',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blade',
 'blake',
 'blakeclark',
 'blame',
 'blind',
 'block',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'blythedanner',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobbalaban',
 'bobbergen',
 'bobby',
 'bobbycannavale',
 'bobbyfarrelly',
 'bobbymoynihan',
 'bobclendenin',
 'bobgunton',
 'bobhoskins',
 'bobodenkirk',
 'bobstephenson',
 'bodies',
 'body',
 'bokeemwoodbine',
 'bold',
 'bomb',
 'bombing',
 'bond',
 'bonniehunt',
 'book',
 'books',
 'border',
 'bored',
 'boring',
 'born',
 'boss',
 'boston',
 'bound',
 'boundaries',
 'bounty',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boydbanks',
 'boydholbrook',
 'boyfriend',
 'boys',
 'braddourif',
 'bradgarrett',
 'bradleycooper',
 'bradleywhitford',
 'bradpitt',
 'bradwilliamhenke',
 'brain',
 'brave',
 'break',
 'breaking',
 'breaks',
 'breckinmeyer',
 'brendanfraser',
 'brendangleeson',
 'brendansextoniii',
 'brentbriscoe',
 'brentspiner',
 'brettcullen',
 'brettratner',
 'brettrice',
 'brian',
 'brianblessed',
 'briancox',
 'briandennehy',
 'briandepalma',
 'briandoyle',
 'brianhowe',
 'brianj',
 'briano',
 'briansteele',
 'brianvanholt',
 'bride',
 'bridge',
 'bridgettewilson',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brucealtman',
 'brucecampbell',
 'brucedavison',
 'brucedern',
 'brucegreenwood',
 'brucemcgill',
 'brucespence',
 'brucewillis',
 'brunokirby',
 'brutal',
 'brutally',
 'bryan',
 'bryancranston',
 'bryansinger',
 'brycedallashoward',
 'buck',
 'buddies',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bumbling',
 'buried',
 'burns',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'busy',
 'butler',
 'buy',
 'byrne',
 'cabin',
 'caesar',
 'cal',
 'california',
 'callahan',
 'called',
 'calls',
 'callumkeithrennie',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'cameron',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'campbellscott',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'capable',
 'capital',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraseymour',
 'card',
 'care',
 'career',
 'carefree',
 'careymulligan',
 'carl',
 'carlagallo',
 'carlagugino',
 'carlosalazraqui',
 'carmen',
 'carmenelectra',
 'carol',
 'carolineaaron',
 'carolinegoodall',
 'carolkane',
 'carpenter',
 'carrie',
 'carriefisher',
 'carry',
 'carrying',
 'cars',
 'carter',
 'cary',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherinemccormack',
 'catherineo',
 'catherinereitman',
 'catherinezeta',
 'cathey',
 'catholic',
 'cathymoriarty',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'cchpounder',
 'cedrictheentertainer',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'celiaimrie',
 'celiaweston',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'certain',
 'chadmichaelmurray',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'chancekelly',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlesdance',
 'charlesdurning',
 'charlesnapier',
 'charless',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotterampling',
 'charltonheston',
 'charm',
 'charming',
 'chase',
 'chased',
 'chazzpalminteri',
 'cheating',
 'cheechmarin',
 'chef',
 'chelcieross',
 'chemical',
 'cher',
 'cherryjones',
 'chevychase',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'chimcbride',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chrisbauer',
 'chriscolumbus',
 'chriscooper',
 'chrisellis',
 'chrisevans',
 'chrishemsworth',
 'chriskattan',
 'chrisklein',
 'chrismessina',
 'chrismiller',
 'chrismulkey',
 'chriso',
 'chrisparnell',
 'chrispenn',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'christian',
 'christianbale',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christinebaranski',
 'christmas',
 'christopher',
 'christopherfairbank',
 'christopherguest',
 'christopherknights',
 'christopherlambert',
 'christopherlee',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciaránhinds',
 'cillianmurphy',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'citizens',
 'city',
 'civil',
 'civilization',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkduke',
 'clarkgregg',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'claudevandamme',
 'clay',
 'cleaduvall',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurtis',
 'cliftoncollinsjr',
 'clinteastwood',
 'clinthoward',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clues',
 'clutches',
 'clydekusatsu',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'codycameron',
 'cohen',
 'col',
 'cold',
 'cole',
 'colehauser',
 'colinfarrell',
 'colinfirth',
 'colinhanks',
 'colinsalmon',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'colleencamp',
 'college',
 'collide',
 'collins',
 'collision',
 'colmfeore',
 'colmmeaney',
 'colonel',
 'colorful',
 'coma',
 'combat',
 'come',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commit',
 'commitment',
 'committed',
 'common',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'compton',
 'computer',
 'conan',
 'concert',
 'conchataferrell',
 'condition',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'connected',
 'connection',
 'connell',
 'connienielsen',
 'connieray',
 'connor',
 'conquer',
 'conradvernon',
 'conscience',
 'consequences',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'corbinbleu',
 'core',
 'coreyburton',
 'coreyfeldman',
 'coreyjohnson',
 'coreystoll',
 'corner',
 'corporate',
 'corporation',
 'corrupt',
 'corruption',
 'cost',
 'costasmandylor',
 'couldn',
 'count',
 'country',
 'countryside',
 'couple',
 'couples',
 'courage',
 'courageous',
 'course',
 'court',
 'courteneycox',
 'courtneyb',
 'cousin',
 'cover',
 ...]